### ISSUE TITLE
Exception occurs when username doesn't contain colon

### ISSUE THREAD

**Issue by M-Pixel** [open-io/oio-swift#228]
```
Traceback (most recent call last):
  File "/usr/bin/oioswift-proxy-server", line 80, in <module>
    **options)
  File "/usr/lib/python2.7/dist-packages/swift/common/wsgi.py", line 914, in run_wsgi
    loadapp(conf_path, global_conf=global_conf)
  File "/usr/lib/python2.7/dist-packages/swift/common/wsgi.py", line 397, in loadapp
    return ctx.create()
  File "/usr/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "/usr/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 207, in invoke
    app = filter(app)
  File "/usr/lib/python2.7/dist-packages/oioswift/common/middleware/tempauth.py", line 88, in tempauth_filter
    return OioTempAuth(app, conf)
  File "/usr/lib/python2.7/dist-packages/oioswift/common/middleware/tempauth.py", line 32, in __init__
    super(OioTempAuth, self).__init__(app, conf)
  File "/usr/lib/python2.7/dist-packages/swift/common/middleware/tempauth.py", line 233, in __init__
    account, username = conf_key.split('_', 1)[1].split('_')
ValueError: need more than 1 value to unpack
```

The above exception occurs, and crashes the process, when a user "name" does not conform to the pattern `[^:]+:[^:]+`.

Instead, it would be better for it to return an explicit error.

**Comment by fvennetier** [comment]
Hello. Thanks for the report. The error comes from the Openstack Swift code, not from oio-swift code. Can you make a bug report there?
https://bugs.launchpad.net/swift

**Comment by M-Pixel** [comment]
https://bugs.launchpad.net/swift/+bug/1911811
